services:
  postgres:
    image: docker.io/library/postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: undertrained
      POSTGRES_PASSWORD: undertrained
      POSTGRES_DB: undertrained
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
